app/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from app import db, login_manager


class User(UserMixin, db.Model):
    """
    Create an User table
    """

    # Ensures table will be named in plural and not in singular
    # as is the name of the model
    __tablename__ = 'employees'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(60), index=True, unique=True)
    username = db.Column(db.String(60), index=True, unique=True)
    first_name = db.Column(db.String(60), index=True)
    last_name = db.Column(db.String(60), index=True)
    password_hash = db.Column(db.String(128))
    is_admin = db.Column(db.Boolean, default=False)

    @property
    def password(self):
        """
        Prevent pasword from being accessed
        """
        raise AttributeError('password is not a readable attribute.')

    @password.setter
    def password(self, password):
        """
        Set password to a hashed password
        """
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        """
        Check if hashed password matches actual password
        """
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<User: {}>'.format(self.username)


# Set up user_loader
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))




class Movies(db.Model):
    """
    Create a Movie table
    """

    __tablename__ = 'movies'

    id = db.Column(db.Integer, primary_key=True)
    ti = db.Column(db.String(60), unique=True)
    hash = db.Column(db.String(200))

    def __repr__(self):
        return '<Movies: {}>'.format(self.name)

app/admin/forms.py
# Forms for admin blueprint

app/__init__.py
# third-party imports
import os
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

# local imports
from config import app_config

db = SQLAlchemy()
login_manager = LoginManager()

config_name = os.getenv('FLASK_CONFIG')
config_name = 'production'

app = Flask(__name__, instance_relative_config=True)
app.config.from_object(app_config[config_name])
app.config.from_pyfile('config.py')

Bootstrap(app)
db.init_app(app)
login_manager.init_app(app)
login_manager.login_message = "You must be logged in to access this page."
login_manager.login_view = "auth.login"
migrate = Migrate(app, db)

from app import models

from .admin import admin as admin_blueprint
app.register_blueprint(admin_blueprint, url_prefix='/admin')

from .auth import auth as auth_blueprint
app.register_blueprint(auth_blueprint)

from .home import home as home_blueprint
app.register_blueprint(home_blueprint)

app/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin', __name__)

from . import views

app/admin/views.py
# Views for admin blueprint

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import render_template
from flask_login import login_required

from . import home


@home.route('/')
def homepage():
    """
    Render the homepage template on the / route
    """
    return render_template('home/index.html', title="Welcome")


@home.route('/dashboard')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    return render_template('home/dashboard.html', title="Dashboard")

app/templates/base.html
<!-- base.html -->

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap core CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/examples/jumbotron-narrow/jumbotron-narrow.css" rel="stylesheet">
  </head>
  <body>
    <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav navbar-nav navbar-right">
                  {% if current_user.is_authenticated %}
                    <li><a><i class="fa fa-user"></i>  你好, {{ current_user.username }}!</a></li>
                    <li><a href="{{ url_for('home.homepage') }}">首页</a></li>
                    <li><a href="{{ url_for('home.dashboard') }}">控制面板</a></li>
                    <li role="presentation"><a href="http://ipfs.fund/" target="_blank">关于方得社区</a></li>
                    <li role="presentation"><a href="https://ipfs.io/" target="_blank">访问IPFS主页</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">退出</a></li>

                  {% else %}
                    <li><a href="{{ url_for('home.homepage') }}">首页</a></li>
                    <li><a href="{{ url_for('auth.register') }}">注册</a></li>
                    <li><a href="{{ url_for('auth.login') }}">登录</a></li>
                    <li role="presentation"><a href="http://ipfs.fund/" target="_blank">关于方得社区</a></li>
                    <li role="presentation"><a href="https://ipfs.io/" target="_blank">访问IPFS主页</a></li>
                  {% endif %}
              </ul>
        </nav>
      </div>
      {% block body %}
      {% endblock %}
      <footer class="footer">
        <p>© 2018 IPFS方得社区</p>
      </footer>
    </div> <!-- /container -->
  </body>
</html>

app/templates/home/dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>The Dashboard</h1>
                    <h3>We made it here!</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/index.html
<!-- index.html-->

{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="jumbotron">
  <h1>IPFS Is Awesome</h1>
  <p class="lead">恭喜您进入Web3.0的世界！您正在观看从全世界ipfs节点传来的视频，enjoy～</p>




</div>

    <nav>
          <ul class="nav navbar-nav navbar-left">
                    <li role="presentation"><a>观看更多：</a></li>
                    <li role="presentation"><a href="https://cloudflare-ipfs.com/ipfs/QmcVQP9rmciGrrQxJgee7j4xbLNDuDfaVToM8nkcHr4xxw" target="_blank">复仇者联盟</a></li>
                    <li role="presentation"><a href="https://cloudflare-ipfs.com/ipfs/QmTPubgs4VsZmVz9pRiHumWe26CeZ6HPa7tkx7paayenRq" target="_blank">蚁人与黄蜂女</a></li>
                    <li role="presentation"><a href="https://cloudflare-ipfs.com/ipfs/QmNaP8ke3fP2EPPtBUV1qM3mD7fAEc9cDiWr2zW389eMUj" target="_blank">水行侠</a></li>
                    <li role="presentation"><a href="https://cloudflare-ipfs.com/ipfs/QmNxFkhj5T2q5BRvpyMDLAv4jfFcWMFANds6qng6ByzPwR" target="_blank">碟中谍</a></li>

              </ul>
    </nav>


<video width="1135" height="600" controls>
    <source src="https://cloudflare-ipfs.com/ipfs/QmZwjHnbLwnMULveZ52VEBKdvQYamtGqDBZPRaBrmiiPMe" type="video/mp4">
</video>

{% endblock %}